### ISSUE TITLE
外层的tab fragment里面再嵌套一层tab fragment会有问题

### ISSUE THREAD

**Issue by jgfntu** [LuckyJayce/ViewPagerIndicator#1]
例如demo里面的tab主界面这个测试例子，现在是外层有4个tab，然后每个tab里面嵌套的是几个viewpager，如果改为嵌套的fragment的话，会发现外层的第一个tab里面的tab是正常的，但是第二个tab里面的tab就有问题了，感觉好像只能实例一个。是否是这种嵌套本身就有问题？

**Comment by kuanglijun312** [comment]
4.2才能fragment嵌套fragment

**Comment by LuckyJayce** [comment]
@jgfntu 
@kuanglijun312 
请看重新写的TabMainActivity 采用 Fragment 嵌套Fragment

**Comment by kuanglijun312** [comment]
非常感谢！！
