### ISSUE TITLE
Tab里的fragment 如果被回收了怎么重建呢？

### ISSUE THREAD

**Issue by wbo4958** [LuckyJayce/ViewPagerIndicator#11]
Hello, 用了这个作为主ＴＡＢ界面，但是如果TAB中的Fragment被回收了怎么恢复呢？目前运行程序，将将它放到后台，然后用adb shell kill -9 pid　去模仿它被回收的情况，结果重新点击应用进去的话，会出现其它tab白屏的现象。求支招呀。

**Comment by songnick** [comment]
你可以在onSaveInstanceState(Bundle outState)存储你的数据，等activity或者fragment重新创建的时候恢复

**Comment by LuckyJayce** [comment]
@wbo4958 你获取的代码是什么时候的？

**Comment by wbo4958** [comment]
@LuckyJayce 我获取最新的也是这样的！  不过代码没有继承LazyFragment, 不知道是不是这个问题造成的。

**Comment by wbo4958** [comment]
@LuckyJayce  我试了最新的代码，然后继承的LazyFragment 也有同样的问题。。。。

**Comment by LuckyJayce** [comment]
@wbo4958 你可以测试我demo是否存在这个问题。如果不存在直接对比一下写法。你可以加我qq方便进行沟通

**Comment by wbo4958** [comment]
自己代码的问题，非常感谢作者
