### ISSUE TITLE
ScrollIndicatorView.setOnItemSelectListener无效

### ISSUE THREAD

**Issue by wfs3006** [LuckyJayce/ViewPagerIndicator#18]
代码如下：
   int selectColorId = R.color.color_1eb7d2;
        int unSelectColorId = R.color.color_434343;
        int colorIndicat = Color.parseColor("#1eb7d2");

        indicator.setScrollBar(new ColorBar(context, colorIndicat, 10));
        indicator.setOnTransitionListener(new OnTransitionTextListener().setColorId(context, selectColorId, unSelectColorId));

        indicator.setOnItemSelectListener(new Indicator.OnItemSelectedListener() {
            @Override
            public void onItemSelected(View view, int i, int i1) {
                //这里无反应？
            }
        });

**Comment by LuckyJayce** [comment]
如果你是使用了indicatorviewpager,那就要用indicatorviewpager来设置切换监听

**Comment by wfs3006** [comment]
好的，可以了
