### ISSUE TITLE
我要实现类似微博的那种布局要怎么弄

### ISSUE THREAD

**Issue by jy05568536** [LuckyJayce/ViewPagerIndicator#19]
中间是一个“+”号图标，点击后是拉起一个新的activity
可以写布局把图标叠加到Indicator中间，但是tab字体图标怎么均匀分配到两边
![image](https://cloud.githubusercontent.com/assets/5037606/17019454/eb1331ac-4f6e-11e6-83fb-8de723b48a56.png)

**Comment by hackware1993** [comment]
@jy05568536 试试 https://github.com/hackware1993/MagicIndicator

**Comment by LuckyJayce** [comment]
@jy05568536  最新的FixedIndicatorView代码添加了setCenterView方法
用法
      
       //这里可以添加一个view，作为centerView，会位于Indicator的tab的中间
        centerView = getLayoutInflater().inflate(R.layout.tab_main_center, indicator, false);
        indicator.setCenterView(centerView);
        centerView.setOnClickListener(onClickListener);

**Comment by jy05568536** [comment]
Thx
