### ISSUE TITLE
MoreTabActivity里面ScrollIndicatorView的问题

### ISSUE THREAD

**Issue by picking** [LuckyJayce/ViewPagerIndicator#2]
![qq 20150504154046](https://cloud.githubusercontent.com/assets/8716945/7450141/02ab60a4-f274-11e4-9c3a-424161565456.png)
![qq 20150504154103](https://cloud.githubusercontent.com/assets/8716945/7450146/08fc3712-f274-11e4-9df3-4be908ee42eb.png)

使用ScrollIndicatorView会出现以上问题

**Comment by panggirl** [comment]
使用ScrollIndicatorView 
![bug_](https://cloud.githubusercontent.com/assets/10395037/7696893/b296659c-fe34-11e4-8d6c-5f54ae84959a.png)

**Comment by LuckyJayce** [comment]
@picking 请下载最新版确认下是否会还会出现你说的问题

**Comment by LuckyJayce** [comment]
@panggirl 已经修复你提的问题
