### ISSUE TITLE
ViewPager引出的bug

### ISSUE THREAD

**Issue by andy91310** [LuckyJayce/ViewPagerIndicator#20]
java.lang.NoSuchMethodError: 
No virtual method    addOnPageChangeListener(Landroid/support/v4/view/ViewPager$OnPageChangeListener;)V in class Landroid/support/v4/view/ViewPager; 
or its super classes (declaration of 'android.support.v4.view.ViewPager' appears in /data/data/com.weijie.ckapp/files/instant-run/dex/slice-support-v4-r7_6b487e8b8eac5541972e73dc0c160b63dd97c123-classes.dex)

 at com.shizhefei.view.indicator.IndicatorViewPager.iniOnPageChangeListener(IndicatorViewPager.java:71)
at com.shizhefei.view.indicator.IndicatorViewPager.<init>(IndicatorViewPager.java:53)
at com.shizhefei.view.indicator.IndicatorViewPager.<init>(IndicatorViewPager.java:43)

**Comment by LuckyJayce** [comment]
@andy91310 你v4的版本太低了，这个方法是后面v4添加的 之前是setOnPageChangeListener，后面v4不建议用setOnPageChangeListener，添加了个addOnPageChangeListener

**Comment by andy91310** [comment]
我用的和你demo中一样的v4版本啊，我怀疑是后面那一句
its super classes (declaration of 'android.support.v4.view.ViewPager' appears in /data/data/com.weijie.ckapp/files/instant-run/dex/slice-support-v4-r7_6b487e8b8eac5541972e73dc0c160b63dd97c123-classes.dex)
用的是v4-r7这个，但我没有加这个版本的v4，我看我引用的第三方包里有这个版本的，我想删除r7版本的，没办法删除，因为在android-studio里没引用，擦了

**Comment by andy91310** [comment]
@LuckyJayce 我用的和你demo中一样的v4版本啊，我怀疑是后面那一句
its super classes (declaration of 'android.support.v4.view.ViewPager' appears in /data/data/com.weijie.ckapp/files/instant-run/dex/slice-support-v4-r7_6b487e8b8eac5541972e73dc0c160b63dd97c123-classes.dex)
用的是v4-r7这个，但我没有加这个版本的v4，我看我引用的第三方包里有这个版本的，我想删除r7版本的，没办法删除，因为在android-studio里没引用，擦了
