### ISSUE TITLE
不足之处?

### ISSUE THREAD

**Issue by anpoz** [LuckyJayce/ViewPagerIndicator#22]
自定义adapter继承自IndicatorViewPager.IndicatorViewPagerAdapter.
应用的情景中getViewForPage方法里面返回的View是依赖于数据源的,而更新数据源后那个View不会立刻进行更新,即使是调用了notifyDataSetChanged(),个人觉得这样不符合实际应用情况.请问有没有解决方法?

**Comment by LuckyJayce** [comment]
这是viwwpager的特征，适配器有个getItemPosition方法可以重写，你可以搜索了解下    viewpager getItemPosition
