### ISSUE TITLE
com.shizhefei.view.indicator.FixedIndicatorView

### ISSUE THREAD

**Issue by lifetin** [LuckyJayce/ViewPagerIndicator#25]
这个控件为嘛不能把子元素设为平均分布?
我弄了一两个小时,原来是这控件问题 
上面这个是我用原生的linnerLayout写的,里面放3个TEXTVIEW,
下面这个是用com.shizhefei.view.indicator.FixedIndicatorView写的,里面动态添加的3个textView,
textview代码是一样的,唯一不同的就是这个父元素,上面的可以正常居中.下面的就无法居中.
我找了N多方法,都不行.除非给textView设定固定宽和高才行.
我是想平均分布有什么办法?
![22](https://cloud.githubusercontent.com/assets/10474968/18410877/8c9d7b0c-779e-11e6-90be-a944f160012c.png)

**Comment by lifetin** [comment]
@Override
    public View getView(int position, View convertView, ViewGroup parent) {
        if (convertView == null) {
            convertView = LayoutInflater.from(context).inflate(R.layout.include_sort_item,null);
        }
        TextView view = (TextView) convertView;
        view.setText(sort.get(position).name);
        //不能自动平均完,需要重新设置一下即可
        ViewGroup.LayoutParams params = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        view.setLayoutParams(params);

        return convertView;
    }


找到问题 了.

        ViewGroup.LayoutParams params = new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        view.setLayoutParams(params);

**Comment by LuckyJayce** [comment]
converView = LayoutInflater.from(context).inflate(R.layout.include_sort_item,parant,false);
在R.layout.include_sort_item这个布局里面可以设置文本居中，不用java代码设置
