### ISSUE TITLE
有没有类似 FragmentStatePagerAdapter 的适配器呢

### ISSUE THREAD

**Issue by 283076875** [LuckyJayce/ViewPagerIndicator#3]
在 FragmentTabhost 内的一个Fragment 使用的控件  切换Tab后会有问题，Fragment无法正常显示，有没有累死FragmentStatePagerAdapter 的适配器解决这个问题

**Comment by LuckyJayce** [comment]
@283076875 
public static interface IndicatorPagerAdapter {

		PagerAdapter getPagerAdapter();

		IndicatorAdapter getIndicatorAdapter();

		void notifyDataSetChanged();

	}

**Comment by 283076875** [comment]
可以了IndicatorViewPager其实可以不调用 setAdapter
