### ISSUE TITLE
1.1.4版本没有setCenterView(View centerView, ViewGroup.LayoutParams layoutParams)方法？

### ISSUE THREAD

**Issue by DevelopmentMan** [LuckyJayce/ViewPagerIndicator#36]
想实现底部导航中间加按钮效果；1.1.4版本没有setCenterView(View centerView, ViewGroup.LayoutParams layoutParams)方法？

**Comment by LuckyJayce** [comment]
在FixedIndicatorView里面有啊，没定义在Indicator接口上
