### ISSUE TITLE
OnTransitionTextListener 颜色问题

### ISSUE THREAD

**Issue by kuanglijun312** [LuckyJayce/ViewPagerIndicator#4]
if (selectColor != -1 && unSelectColor != -1) {
			selectTextView.setTextColor(gradient.getColor((int) (selectPercent * 100)));
		}

貌似#ffffff的值是-1，就不会触发这里

**Comment by LuckyJayce** [comment]
@kuanglijun312  谢谢你的反馈
已经修复
