### ISSUE TITLE
如何配置ProGurad规则？

### ISSUE THREAD

**Issue by freedomofme** [LuckyJayce/ViewPagerIndicator#46]
`-keep class com.shizhefei.** { *;}
 -dontwarn com.shizhefei.view.indicator.RecyclerIndicatorView`

使用了上面的规则后，能够打出release 版本，但是运行时会导致

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.greenteam.snackshopping/com.greenteam.snackshopping.activity.main.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.shizhefei.view.indicator.Indicator.setItemClickable(boolean)' on a null object reference

**Comment by LuckyJayce** [comment]
不需要额外配置混淆
你调试下，应该是你view没有find到 导致空指针
