### ISSUE TITLE
是否支持非图片，比如网页轮播？

### ISSUE THREAD

**Issue by nanchen2251** [LuckyJayce/ViewPagerIndicator#47]

**Comment by LuckyJayce** [comment]
支持

**Comment by nanchen2251** [comment]
请问如何实现呢？我发现网页会有闪烁效果。

**Comment by LuckyJayce** [comment]
@nanchen2251 

       private class MainPageAdapter extends IndicatorViewPager.IndicatorViewPagerAdapter {
    
            @Override
            public int getCount() {
                return 10;
            }
    
            @Override
            public View getViewForTab(int position, View convertView, ViewGroup container) {
                if (convertView == null) {
                    convertView = LayoutInflater.from(container.getContext()).inflate(R.layout.tab_top, container, false);
                }
                TextView textView = (TextView) convertView;
                textView.setText("tab" + position);
                return convertView;
            }
    
            @Override
            public View getViewForPage(int position, View convertView, ViewGroup container) {
                if (convertView == null) {
                    convertView = createWebView(container);
                }
                WebView webView = (WebView) convertView;
                webView.loadUrl("https//:www.baidu.com");
                return convertView;
            }
    
            private WebView createWebView(ViewGroup container) {
                WebView webView = new WebView(container.getContext());
                webView.getSettings().setJavaScriptEnabled(true);
                return webView;
            }
        }

**Comment by LuckyJayce** [comment]
你可以设置 viewPager.setOffscreenPageLimit(2);
保持左右两边有2个缓存页面

**Comment by nanchen2251** [comment]
你好，该方法我已经做了。但是getViewForPage会重复调用，导致，及时你在网页进入了其他选项，还是会回到百度首页。

**Comment by LuckyJayce** [comment]
你不重复利用的话，难道所有的都要重新创建 并且保留在内存中？

**Comment by nanchen2251** [comment]
我看了每次convertView地址都不一样。所以导致网页根本每次都会重新加载。这样的话，用网页或者其他的任何东西就没用了。
