### ISSUE TITLE
ScrollIndicatorView的dispatchDraw死循环

### ISSUE THREAD

**Issue by Ruowenmei** [LuckyJayce/ViewPagerIndicator#49]
setOnIndicatorItemClickListener onItemClick会导致ScrollIndicatorView的dispatchDraw死循环执行

**Comment by LuckyJayce** [comment]
代码贴出来看下

**Comment by Ruowenmei** [comment]
我自己继承了ScrollIndicatorView
`public class ColorBgIndicatorView extends ScrollIndicatorView {

    private static final int DEFAULT_VISIBLE_COUNT = 3;
    private static final int TAB_BACKGROUND_COLOR = 0x95EFEFF4;

    private int tabVisibleCount = DEFAULT_VISIBLE_COUNT;
    private int transX = 0;
    private int oldTransX = transX;
    private int tabWidth = 0;
    private Paint paint;
    private Rect rect;

    public ColorBgIndicatorView(Context context, AttributeSet attrs) {
        super(context, attrs);
        init();
    }

    private void init() {
        paint = new Paint();
        paint.setAntiAlias(true);
        paint.setDither(true);
        paint.setStyle(Paint.Style.FILL);
        paint.setColor(TAB_BACKGROUND_COLOR);

        rect = new Rect();
    }

    @Override
    protected void onSizeChanged(int w, int h, int oldw, int oldh) {
        super.onSizeChanged(w, h, oldw, oldh);
        setRect();
    }

    @Override
    public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
        super.onPageScrolled(position, positionOffset, positionOffsetPixels);
        transX = (int) (tabWidth * (position + positionOffset));
        if (hasScrolled()) {
            postInvalidate();
        }
    }

    @Override
    protected void dispatchDraw(Canvas canvas) {
        MyLog.v("zhengbin dispatchDraw transX=" + transX);
        canvas.save();
        canvas.translate(transX, 0); //画笔平移到正确的位置
        canvas.drawRect(rect, paint);
        canvas.restore();
        super.dispatchDraw(canvas);
    }

    private boolean hasScrolled() {
        if (oldTransX != transX) {
            oldTransX = transX;
            return true;
        } else {
            return false;
        }
    }

    private void setRect() {
        if (null != rect) {
            rect.left = 0;
            rect.right = tabWidth;
            rect.top = 0;
            rect.bottom = getHeight();
            postInvalidate();
        }
    }

    public void setTabVisibleCount(int visibleCount) {
        if (0 == visibleCount) {
            return;
        }

        this.tabVisibleCount = visibleCount;
        this.tabWidth = GlobalData.getScreenWidth() / visibleCount;
        setRect();
    }
}`

代码调用位置：
`sivTab.setOnItemSelectListener(new Indicator.OnItemSelectedListener() {

            @Override
            public void onItemSelected(View selectItemView, int select, int preSelect) {
                
                viewPager.setCurrentItem(select);
            }
        });
        sivTab.setOnIndicatorItemClickListener(new Indicator.OnIndicatorItemClickListener() {
            @Override
            public boolean onItemClick(View clickItemView, int position) {

                return false;
            }
        });`

viewpager使用：
`viewPager.addOnPageChangeListener(new ViewPager.OnPageChangeListener() {
            @Override
            public void onPageSelected(int position) {
                sivTab.setCurrentItem(position, true);
            }

            @Override
            public void onPageScrolled(int position, float positionOffset, int positionOffsetPixels) {
                sivTab.onPageScrolled(position, positionOffset, positionOffsetPixels);
            }

            @Override
            public void onPageScrollStateChanged(int state) {
                sivTab.onPageScrollStateChanged(state);
            }
        });`

使用过程中发现，直接点击indicator的item 会导致我复写的indicator类的dispatchDraw()方法，死循环执行，滑动viewpager不会，谢谢

**Comment by LuckyJayce** [comment]
你这要实现什么效果，可以截图看下
你可以看下ScrollBar或许可以实现

**Comment by Ruowenmei** [comment]
给scrollbar选中的项设置颜色背景，能跟随viewpager滑动，如图:
![faa98a700266b8703cb706f15a6f14c8](https://user-images.githubusercontent.com/13732248/30056590-d8862018-9265-11e7-81f7-8d8bd52d3d4c.jpg)

**Comment by Ruowenmei** [comment]
麻烦看一下这个效果是否可以直接使用控件实现，谢谢，不能的话希望能一起解决一下问题

**Comment by LuckyJayce** [comment]
demo就有啊

**Comment by Ruowenmei** [comment]
谢谢，麻烦了
