### ISSUE TITLE
集成多个scrollindicatorview 问题

### ISSUE THREAD

**Issue by wbo4958** [LuckyJayce/ViewPagerIndicator#6]
您好！

在 fragment_tabmain.xml中将FixedIndicatorView 改为 ScrollIndicatorView的形式，并设置auto split
结果出现第二个tab,没有auto split, 除非手动滑动一下才出现
第一个tab正常加载
![2](https://cloud.githubusercontent.com/assets/1320706/8396342/4a99b4d4-1dd4-11e5-933f-f6963548b798.png)
第二个tab的scrollindicatorview没有auto split
![3](https://cloud.githubusercontent.com/assets/1320706/8396344/4bb6c7c6-1dd4-11e5-8cc6-673ce0fae645.png)
手动左右滑动就行了。
![4](https://cloud.githubusercontent.com/assets/1320706/8396347/4f92dace-1dd4-11e5-8ffb-fb738af41772.png)

请您fix 下，非常感谢

**Comment by LuckyJayce** [comment]
已经修复

**Comment by wbo4958** [comment]
已验证，最新的commit能fix, 非常感谢
