### ISSUE TITLE
建议：增加androidx依赖的分支版本

### ISSUE THREAD

**Issue by leleliu008** [LuckyJayce/ViewPagerIndicator#65]
您好，建议增加androidx依赖的分支版本，androidx参考：[https://developer.android.google.cn/reference/androidx/classes](https://developer.android.google.cn/reference/androidx/classes)

**Comment by LiHexiang** [comment]
我也遇到了这个需求

**Comment by caocao123** [comment]
+1

**Comment by LuckyJayce** [comment]
加上了
