### ISSUE TITLE
在OnTransitionTextListener中加了一个选中字体加粗的代码，但是貌似选中和未选中字体都加粗了

### ISSUE THREAD

**Issue by lu79931748** [LuckyJayce/ViewPagerIndicator#66]
![image](https://user-images.githubusercontent.com/13619151/54683201-fd8cbc00-4b4b-11e9-9317-b670576f0623.png)
![image](https://user-images.githubusercontent.com/13619151/54683226-139a7c80-4b4c-11e9-9dfd-54b3361dddd6.png)
![image](https://user-images.githubusercontent.com/13619151/54683239-19905d80-4b4c-11e9-85de-2f7ec5961e94.png)
![image](https://user-images.githubusercontent.com/13619151/54683250-23b25c00-4b4c-11e9-8d3a-4f680e9cd7b1.png)

**Comment by LuckyJayce** [comment]
需要带上 selectPercent计算，这个是position1-> position2的过渡动画，selectPercent是position对应比例0-1，移动过程position1和position2都会调用到该方法

**Comment by lu79931748** [comment]
> 需要带上 selectPercent计算，这个是position1-> position2的过渡动画，selectPercent是position对应比例0-1，移动过程position1和position2都会调用到该方法

明白了，那就做个判断[0,1)是normal，1就是bold

**Comment by LuckyJayce** [comment]
如果不用过渡效果 直接用 indicatorViewPager.setOnIndicatorPageChangeListener()就好了
然后用 View tabItem = indicator.getItemView(position) 获取tab设置

**Comment by lu79931748** [comment]
> 如果不用过渡效果 直接用 indicatorViewPager.setOnIndicatorPageChangeListener()就好了
> 然后用 View tabItem = indicator.getItemView(position) 获取tab设置

这个监听传了两个参数一个是preCurrentItem,一个是currentItem。 View currentView = (ViewGroup) mIndicator.getItemView(currentItem);这样获取之后我怎么拿到tab里的textview？循环一下用instanceof Textview做判断吗？
