### ISSUE TITLE
这里面的v4包很奇怪

### ISSUE THREAD

**Issue by xiaolongyuan** [LuckyJayce/ViewPagerIndicator#7]
![image](https://cloud.githubusercontent.com/assets/3142363/8591792/3291f22a-265d-11e5-87ac-e6c60d497a95.png)

**Comment by xiaolongyuan** [comment]
用gradle因该引入哪个版本的？

**Comment by LuckyJayce** [comment]
@xiaolongyuan 你现在可以下载下该类库最新的代码，v4可以任意的版本
