### ISSUE TITLE
最新版的jar包在哪可以下载？

### ISSUE THREAD

**Issue by kakashilw** [LuckyJayce/ViewPagerIndicator#75]
你好 首先感谢提供了这么好的lib 我这边之前一直都是用jar包的方式导入 不过现在的压缩包里只有ViewPagerIndicator_1.1.0.jar 到1.1.0版本的 没有1.1.9的提供 请问最新版的jar包在哪可以下载

**Comment by LuckyJayce** [comment]
如果需要jar 可以到jcenter 把arr下载然后解压获取jar. 因为该项目没有用到资源文件所以直接解压拿jar 用也可以https://bintray.com/version/files/luckyjayce/maven/ViewPagerIndicator/1.1.9?order=asc&sort=name&basePath=com%2Fshizhefei%2FViewPagerIndicator%2F1.1.9&tab=files 
不过，现在9102都用android studio了啊，直接gradle引入更方便
