### ISSUE TITLE
gpu一直在重绘

### ISSUE THREAD

**Issue by wbo4958** [LuckyJayce/ViewPagerIndicator#8]
打开开发者模式->GPU呈现模式分析>在屏幕上显示为线型图

然后打开viewpagerindicator 这个demo， 点击不同的的TAB时，会发现GPU一直在重绘，这样会很耗电的

**Comment by LuckyJayce** [comment]
@wbo4958  
感谢你提出的问题,现在已经修复
,你可以跟新下最新的代码测试下

**Comment by wbo4958** [comment]
wow,  已测试，作者解决问题真是神速，非常感谢

**Comment by LuckyJayce** [comment]
@wbo4958
刚又提交了，你再更新下代码。
