### ISSUE TITLE
哥，还维护么？

### ISSUE THREAD

**Issue by po1xiao** [LuckyJayce/ViewPagerIndicator#87]
挺好用的，抽空维护一下子吧。

**Comment by LuckyJayce** [comment]
现在compose是趋势，
这种命令式的UI View会被替代。
况且我现在的重心在flutter上，没用到这个类库，并且fragment版本api变化比较大，没用到实际场景更不太适合维护它。
你可以看到其它作者的命令式ui控件的类库也基本不维护了。
拥抱jeckpack、拥抱compose。
