### ISSUE TITLE
ScrollIndicatorView 的TAB使用嵌套layout 导致程序crash

### ISSUE THREAD

**Issue by wbo4958** [LuckyJayce/ViewPagerIndicator#9]
hello,

在demo的moretab->MoreTabActivity中，在设置tab indicator时，如果把tab_top的TextView外加一层RelativeLayout或LinearLayout时，程序直接crash掉

			if (convertView == null) {
				convertView = inflate.inflate(R.layout.tab_top, container, false);
			}
			TextView textView = (TextView) convertView.findViewById(R.id.tab); 

---------------------------------------------------------------------------------------
file name: tab_top.xml
---------------------------------------------------------------------------------------
![image](https://cloud.githubusercontent.com/assets/1320706/9271630/08648fd6-42ae-11e5-9e01-5235633ffe3c.png)

**Comment by LuckyJayce** [comment]
你要重写 OnTransitionTextListener

**Comment by wbo4958** [comment]
恩，重写确实可以了，但是这样太麻烦了，比如在getViewForTab时，如果对tab的textview也会使用的话，会用两次，这样比较分散
